services:
  postgres:
    image: postgres:15
    container_name: asistente-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: dete123
      POSTGRES_DB: asistente_pagos
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: